-- System Reference Code Tables

CREATE TABLE REFMATICA_REF_STATUS_CODE_REF(REF_STATUS_CD, REF_STATUS_CD_NAME, REF_STATUS_CD_DESCRIPTION, IS_ACTIVE, PARENT_REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_STATUS_CODE_REF(ENTITY_STATUS_CODE, ENTITY_STATUS_CODE_NAME, ENTITY_STATUS_CODE_DESCRIPTION, REF_STATUS_CD, PARENT_ENTITY_STATUS_CODE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);


CREATE TABLE REFMATICA_ENTITY_TYPE_REF(ENTITY_TYPE, ENTITY_TYPE_NAME, ENTITY_TYPE_DESCRIPTION, PARENT_ENTITY_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_NAME_TYPE_REF(ENTITY_NAME_TYPE, ENTITY_NAME_TYPE_NAME, ENTITY_NAME_TYPE_DESCRIPTION, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_XREF_TYPE_REF(ENTITY_XREF_TYPE, ENTITY_XREF_TYPE_NAME, ENTITY_XREF_TYPE_DESCRIPTION, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);


CREATE TABLE REFMATICA_ENTITY_REL_TYPE_REF(ENTITY_REL_TYPE, ENTITY_REL_TYPE_NAME, ENTITY_REL_TYPE_DESCRIPTION, PARENT_ENTITY_REL_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_GROUP_TYPE_REF(ENTITY_GROUP_TYPE, ENTITY_GROUP_TYPE_NAME, ENTITY_GROUP_TYPE_DESCRIPTION, PARENT_ENTITY_GROUP_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);


CREATE TABLE REFMATICA_ENTITY_ENVIRONMENT_REF(ENVIRONMENT_CODE, ENVIRONMENT_NAME, ENVIRONMENT_DESCRIPTION, PARENT_ENVIRONMENT_CODE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_DATA_RESOURCE_TYPE_REF(DAT_RES_TYPE, DAT_RES_TYPE_NAME, DAT_RES_TYPE_DESCRIPTION, PARENT_DAT_RES_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_LOCATION_TYPE_REF(LOC_TYPE, LOC_TYPE_NAME, LOC_TYPE_DESCRIPTION, PARENT_LOC_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_ADDRESS_TYPE_REF(ADDR_TYPE, ADDR_TYPE_NAME, ADDR_TYPE_DESCRIPTION, PARENT_ADDR_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);


CREATE TABLE REFMATICA_DATA_TYPE_REF(DATA_TYPE_CODE, DATA_TYPE_NAME, DATA_TYPE_DESCRIPTION, DATA_TYPE_LANGUAGE_CODE, PARENT_DATA_TYPE_CODE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_DATA_TYPE_LANGUAGE_REF(DATA_TYPE_LANGUAGE_CODE, DATA_TYPE_LANGUAGE_NAME, DATA_TYPE_LANGUAGE_DESCRIPTION, PARENT_DATA_TYPE_LANGUAGE_CODE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);


CREATE TABLE REFMATICA_ROLE_REF(ROLE_TYPE, ROLE_NAME, ROLE_DESCRIPTION, PARENT_ROLE_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ORGANIZATION_TYPE_REF(ORG_TYPE, ORG_TYPE_NAME, ORG_TYPE_DESCRIPTION, PARENT_ORG_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_USER_TYPE_REF(USER_TYPE, USER_TYPE_NAME, USER_TYPE_DESCRIPTION, PARENT_USER_TYPE, REF_STATUS_CD, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);





-- Base Entity Tables

CREATE TABLE REFMATICA_ENTITY(ENTITY_ID, ENTITY_TYPE, ENTITY_STATUS_CODE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_VERSIONS(ENTITY_ID, ENTITY_VERSION_ID, ENTITY_VERSION, ENTITY_VERSION_STATUS_CODE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);




-- Organizational Structure

CREATE TABLE REFMATICA_ORGANIZATION(ENTITY_VERSION_ID, ORG_TYPE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_USERS(ENTITY_VERSION_ID, USER_TYPE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ORG_USERS(ORG_ENTITY_VERSION_ID, USER_ENTITY_VERSION_ID, ROLE_TYPE, USER_INHERIT_ORG_ROLE_IND, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);





-- Entity Metadata - Generally attached to a single Entity (Direct Related, Entity-Entity-Rel not needed)

CREATE TABLE REFMATICA_ENTITY_NAMES(ENTITY_VERSION_ID, ENTITY_NAME_TYPE, ENTITY_NAME_VALUE, NAME_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_ENVIRONMENTS(ENTITY_VERSION_ID, ENVIRONMENT_CODE, ENV_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_TAGS(ENTITY_VERSION_ID, TAG_TYPE, TAG_NAME, TAG_VALUE, TAG_INDEX, TAG_LEVEL, TAG_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_XREF(ENTITY_VERSION_ID, ENTITY_XREF_TYPE, ENTITY_XREF_VALUE, XREF_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_PROPERTIES(ENTITY_VERSION_ID, PROP_SET_NAME, PROP_NAME, PROP_VALUE, PROP_ARR_INDEX, IS_PROP_ARRAY, PROP_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_ANNOTATIONS(ENTITY_VERSION_ID, ANNOTATION_NAME, ANNOTATION_INDEX, ANNOTATION_PARAM_NAME, ANNOTATION_PARAM_VALUE, ANNOTATION_PARAM_VALUE_INDEX, ANNOTATION_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_LINKS(ENTITY_VERSION_ID, LINK_URL, LINK_TEXT, LINK_TOOLTIP, LINK_DESCRIPTION, LINK_ORDER_INDEX, LINK_GROUP_NAME, LINK_GROUP_INDEX, LINK_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_COMMENTS(ENTITY_VERSION_ID, COMMENT_TYPE, COMMENT_TITLE, COMMENT_SUBJECT, COMMENT_REASON, COMMENT_TEXT, COMMENTER, COMMENT_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_ACTIONS_AUDIT(ENTITY_VERSION_ID, ACTION_TYPE, ACTION_SUBJECT, ACTION_REASON, ACTION_NOTES, ACTION_USER, ACTION_TAKEN, IS_WORKFLOW, WORKFLOW_PROCESS_ID, WORKFLOW_STEP_ID, WORKFLOW_PROCESS_NAME, WORKFLOW_STEP_NAME, WORKFLOW_PROCESS_INFO, WORKFLOW_STEP_INFO, ACTION_TS, ACTION_AUDIT_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_DATA_TYPE_INFO(ENTITY_VERSION_ID, DATA_TYPE_CODE, DATA_TYPE_INFO_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_KEYS(ENTITY_VERSION_ID, KEY_TYPE_CODE, KEY_NAME, KEY_IS_COMPOSITE, KEY_ORDER_INDEX, KEY_FIELD_ENTITY_VERSION_ID, KEY_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_INDEXES(ENTITY_VERSION_ID, INDEX_TYPE_CODE, INDEX_NAME, INDEX_IS_COMPOSITE, INDEX_ORDER_INDEX, INDEX_FIELD_ENTITY_VERSION_ID, INDEX_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_CONSTRAINTS(ENTITY_VERSION_ID, CONSTRAINT_TYPE_CODE, CONSTRAINT_NAME, CONSTRAINT_ORDER_INDEX, CONSTRAINT_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_CONSTRAINT_PARAMS(CONSTRAINT_ENTITY_VERSION_ID, CONSTRAINT_PARAM_DATA_TYPE_CODE, CONSTRAINT_PARAM_NAME, CONSTRAINT_PARAM_ORDER_INDEX, CONSTRAINT_PARAM_, CONSTRAINT_PARAM_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);




-- Entity Metadata - Can be attached to one or more Entities (Not directly Related, Entity-Entity-Rel Required)

CREATE TABLE REFMATICA_ENTITY_GROUP(GROUP_ENTITY_VERSION_ID, ENTITY_GROUP_TYPE, ENTITY_GROUP_TYPE_NAME, ENTITY_GROUP_DESCRIPTION, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_DOCUMENTATION(DOC_ENTITY_VERSION_ID, DOC_TYPE, DOC_NAME, DOC_TITLE, DOC_SUBJECT, DOC_AUTHOR, DOC_SUMMARY, DOC_FULL_TEXT, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_LOGIC(LOGIC_ENTITY_VERSION_ID, LOGIC_TYPE, LOGIC_NAME, LOGIC_DESCRIPTION, LOGIC_DECLARATION, LOGIC_DEFINITION, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_OP_FACTS(OP_FACT_ENTITY_VERSION_ID, OP_FACT_TYPE, OP_FACT_NAME, OP_FACT_DESCRIPTION, OP_FACT_VALUE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_EXTERN_ARTIFACT(ARTIFACT_ENTITY_VERSION_ID, ARTIFACT_TYPE, ARTIFACT_NAME, ARTIFACT_TITLE, ARTIFACT_SUBJECT, ARTIFACT_AUTHOR, ARTIFACT_DESCRIPTION, ARTIFACT_REASON, ARTIFACT_DATA_RESOURCE_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_ADDRESS(ADDR_ENTITY_VERSION_ID, ADDR_TYPE, ADDR_NAME, ADDR_LINE_1, ADDR_LINE_2, ADDR_CITY, ADDR_PROVINCE, ADDR_POSTAL_CODE, ADDR_COUNTRY, ADDR_REGION, ADDR_GEO_LATITUDE, ADDR_GEO_LONGITUDE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);




-- Data Resource Technical Location and Physical Location Info

CREATE TABLE REFMATICA_DATA_PHYSICAL_LOCATION(LOC_ENTITY_VERSION_ID, LOC_TYPE, LOC_NAME, ENVIRONMENT_CODE, LOC_STATUS_CODE, LOC_ORDER_INDEX, ADDR_ENTITY_VERSION_ID, LOC_USAGE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_DATA_RESOURCE(DAT_RES_ENTITY_VERSION_ID, DAT_RES_TYPE, DAT_RES_NAME, DAT_RES_STATUS_CODE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_DATA_RESOURCE_INFO(DAT_RES_ENTITY_VERSION_ID, DAT_RES_HOST, DAT_RES_PORT, DAT_RES_URI, DAT_RES_PATH, DAT_RES_QUERY_STRING, DATA_RES_MACHINE_NAME, DATA_RES_SERVER_NAME, DATA_RES_INSTANCE_NAME, DAT_RES_CONTEXT, DAT_RES_SUBJECT, DAT_RES_OBJECT_NAME, DAT_RES_OBJECT_OWNER, DAT_RES_OBJECT_GROUP_OWNER, DAT_RES_AUTH_CONTEXT, DAT_RES_AUTH_SUBJECT, DAT_RES_AUTH_OBJECT, DAT_RES_AUTH_PRINCIPLE, DAT_RES_AUTH_CREDENTIALS, DAT_RES_AUTH_PROVIDER, DAT_RES_AUTH_ALGO, DAT_RES_SCHEMA, DAT_RES_DATABASE, DAT_RES_COLLECTION, DAT_RES_QUEUE, DAT_RES_TOPIC, DAT_RES_TITLE, DAT_RES_AUTHOR, DAT_RES_OWNER, DAT_RES_GROUP, DAT_RES_FILENAME, DAT_RES_DIRECTORY, DAT_RES_EXT_TYPE, DAT_RES_BYTE_SIZE, DAT_RES_COMMENTS, DAT_RES_PROTOCOL, DAT_RES_ROLE, DAT_RES_SERVICE_PROVIDER, DAT_RES_PROJECT, DAT_RES_DATASET, DAT_RES_SERVICE_NAME, DAT_RES_PROVIDER, DAT_RES_VENDOR, DAT_RES_VER, DAT_RES_SUB_VER,, DAT_RES_CONNECTOR_TYPE, DAT_RES_DRIVER, DAT_RES_CLIENT_IMPL, DAT_RES_SERVER_IMPL, DAT_RES_PROXY, DAT_RES_UNIX_PERMISSION_USER, DAT_RES_UNIX_PERMISSION_GROUP, DAT_RES_UNIX_PERMISSION_WORLD, DAT_RES_TBLSP_SPEC, DAT_RES_IDXSP_SPEC, DAT_RES_PARTITION_SPEC, DAT_RES_CACHE_SPEC, DAT_RES_LOGGING_SPEC, DAT_RES_SIZE_SIZE, DAT_RES_FILE_SPEC, DAT_RES_PAGE_SPEC, DAT_RES_BUFFER_SPEC, DAT_RES_LOB_SPEC, DAT_RES_IMPL_SPEC, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);




-- Relationship Tables

CREATE TABLE REFMATICA_ENTITY_ENTITY_REL(FROM_ENTITY_VERSION_ID, TO_ENTITY_VERSION_ID, ENTITY_REL_TYPE, FROM_ENTITY_CARTINALITY, TO_ENTITY_CARTINALITY, REL_ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTITY_GROUP_REL(GROUP_ENTITY_VERSION_ID, MEMBER_ENTITY_VERSION_ID, MEMBER_ENTITY_INDEX, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_DATA_RESOURCE_LOCATION_REL(LOC_ENTITY_VERSION_ID, DAT_RES_ENTITY_VERSION_ID, LOC_PRIORITY, LOC_FAILOVER_ORDER, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);



-- Core Catalog Structure

CREATE TABLE REFMATICA_LIBRARY(ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_VOLUME(ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_SET(ENTITY_VERSION_ID, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);

CREATE TABLE REFMATICA_ENTRY(ENTITY_VERSION_ID, DATA_TYPE_CODE, CREATION_USR, CREATION_APP, CREATION_TS, LST_MOD_USR, LST_MOD_APP, LST_MOD_CHG_CD, LST_MOD_TS);






